import '../styles/theme.css';
import '../styles/colors_and_type.css';
import '../styles/marketing.css';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Analytics } from '@vercel/analytics/next';
import AcquisitionCapture from '../components/analytics/AcquisitionCapture';
import { THEME_BOOTSTRAP_SCRIPT } from '../src/lib/theme-bootstrap';

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://mcpemails.com';
// This value is generated in Google Search Console. It is public by design
// (Google verifies it from a meta tag), but is optional so local builds and
// preview deployments do not accidentally claim the production property.
const GOOGLE_SITE_VERIFICATION = process.env.GOOGLE_SITE_VERIFICATION;

export const metadata = {
  metadataBase: new URL(APP_URL),
  ...(GOOGLE_SITE_VERIFICATION
    ? { verification: { google: GOOGLE_SITE_VERIFICATION } }
    : {}),
  title: {
    default: 'AI Email MCP Server — Connect Gmail & IMAP to Claude | mcpemails',
    template: '%s · mcpemails',
  },
  description: 'Connect Gmail, Fastmail, iCloud, or IMAP email to Claude, Cursor, ChatGPT, and MCP clients. Read, send, search, and organize email live; Outlook support is in progress.',
  openGraph: {
    type: 'website',
    siteName: 'mcpemails',
    title: 'AI Email MCP Server — Connect Gmail & IMAP to Claude | mcpemails',
    description: 'Connect Gmail, Fastmail, iCloud, or IMAP email to Claude, Cursor, ChatGPT, and MCP clients. Read, send, search, and organize email live; Outlook support is in progress.',
    url: APP_URL,
    // Social card is generated by app/opengraph-image.tsx (Next.js file
    // convention); no explicit images entry needed here.
  },
  twitter: {
    // No `site`/`creator` handle: @mcpemails does not exist on X. Add it
    // back here if/when a real account is created.
    card: 'summary_large_image',
    title: 'AI Email MCP Server — Connect Gmail & IMAP to Claude | mcpemails',
    description: 'Connect Gmail, Fastmail, iCloud, or IMAP email to Claude, Cursor, ChatGPT, and MCP clients. Read, send, search, and organize email live; Outlook support is in progress.',
  },
  icons: {
    icon: '/favicon.svg',
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        {/*
          Sets data-theme before first paint so a dark-theme visitor never sees
          a white flash. It carries no `nonce`: `script-src` allows it by the
          SHA-256 of THEME_BOOTSTRAP_SCRIPT (see src/lib/csp.ts), which the
          proxy computes from this same constant on every request.

          Do NOT inline the script text here, reformat it, or wrap the
          expression in anything that adds whitespace. The browser hashes the
          exact bytes React writes between the tags; one stray newline and the
          script is silently blocked, which shows up as a theme flash on every
          page and nothing else.
        */}
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP_SCRIPT }} />
      </head>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
        <AcquisitionCapture />
        <Analytics />
      </body>
    </html>
  );
}
