import '../styles/theme.css';
import '../styles/colors_and_type.css';
import '../styles/marketing.css';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Analytics } from '@vercel/analytics/next';
import AcquisitionCapture from '../components/analytics/AcquisitionCapture';

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://mcpemails.com';
// This value is generated in Google Search Console. It is public by design
// (Google verifies it from a meta tag), but is optional so local builds and
// preview deployments do not accidentally claim the production property.
const GOOGLE_SITE_VERIFICATION = process.env.GOOGLE_SITE_VERIFICATION;

export const metadata = {
  metadataBase: new URL(APP_URL),
  ...(GOOGLE_SITE_VERIFICATION
    ? { verification: { google: GOOGLE_SITE_VERIFICATION } }
    : {}),
  title: {
    default: 'AI Email MCP Server — Connect Gmail & IMAP to Claude | mcpemails',
    template: '%s · mcpemails',
  },
  description: 'Connect Gmail, Fastmail, iCloud, or IMAP email to Claude, Cursor, ChatGPT, and MCP clients. Read, send, search, and organize email live; Outlook support is in progress.',
  openGraph: {
    type: 'website',
    siteName: 'mcpemails',
    title: 'AI Email MCP Server — Connect Gmail & IMAP to Claude | mcpemails',
    description: 'Connect Gmail, Fastmail, iCloud, or IMAP email to Claude, Cursor, ChatGPT, and MCP clients. Read, send, search, and organize email live; Outlook support is in progress.',
    url: APP_URL,
    // Social card is generated by app/opengraph-image.tsx (Next.js file
    // convention); no explicit images entry needed here.
  },
  twitter: {
    // No `site`/`creator` handle: @mcpemails does not exist on X. Add it
    // back here if/when a real account is created.
    card: 'summary_large_image',
    title: 'AI Email MCP Server — Connect Gmail & IMAP to Claude | mcpemails',
    description: 'Connect Gmail, Fastmail, iCloud, or IMAP email to Claude, Cursor, ChatGPT, and MCP clients. Read, send, search, and organize email live; Outlook support is in progress.',
  },
  icons: {
    icon: '/favicon.svg',
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var t = localStorage.getItem("mcpe-theme");
                  if (t !== "light" && t !== "dark") {
                    t = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
                  }
                  document.documentElement.setAttribute("data-theme", t);
                } catch(e) {
                  document.documentElement.setAttribute("data-theme", "light");
                }
              })();
            `,
          }}
        />
      </head>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
        <AcquisitionCapture />
        <Analytics />
      </body>
    </html>
  );
}
