import '../styles/theme.css';
import '../styles/colors_and_type.css';
import '../styles/marketing.css';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Analytics } from '@vercel/analytics/next';

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://mcpemails.com';

export const metadata = {
  metadataBase: new URL(APP_URL),
  title: {
    default: 'mcpemails · Connect Gmail, Outlook & IMAP to Claude',
    template: '%s · mcpemails',
  },
  description: 'Give Claude, Cursor, or any MCP client real access to your inbox: read, send, search, and organize email in Gmail, Outlook, Fastmail, iCloud, and IMAP.',
  openGraph: {
    type: 'website',
    siteName: 'mcpemails',
    title: 'mcpemails · Connect Gmail, Outlook & IMAP to Claude',
    description: 'Give Claude, Cursor, or any MCP client real access to your inbox: read, send, search, and organize email in Gmail, Outlook, Fastmail, iCloud, and IMAP.',
    url: APP_URL,
    // Social card is generated by app/opengraph-image.tsx (Next.js file
    // convention); no explicit images entry needed here.
  },
  twitter: {
    // No `site`/`creator` handle: @mcpemails does not exist on X. Add it
    // back here if/when a real account is created.
    card: 'summary_large_image',
    title: 'mcpemails · Connect Gmail, Outlook & IMAP to Claude',
    description: 'Give Claude, Cursor, or any MCP client real access to your inbox: read, send, search, and organize email in Gmail, Outlook, Fastmail, iCloud, and IMAP.',
  },
  icons: {
    icon: '/favicon.svg',
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var t = localStorage.getItem("mcpe-theme") || "light";
                  document.documentElement.setAttribute("data-theme", t);
                } catch(e) {
                  document.documentElement.setAttribute("data-theme", "light");
                }
              })();
            `,
          }}
        />
      </head>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
        <Analytics />
      </body>
    </html>
  );
}
