// GENERATED DATA, HAND-MAINTAINED THEREAFTER.
//
// The single source of truth for the /connect/<provider> landing pages.
//
// Every `imap`/`smtp` entry below was verified on 2026-08-31 by opening a real
// TLS connection to the host and reading its IMAP CAPABILITY banner (see
// `evidence`). A successful handshake validates the certificate chain against
// that exact hostname, so a host recorded here demonstrably answers IMAP over
// TLS under the name we publish. Settings came from the Mozilla ISPDB
// (autoconfig.thunderbird.net) where it lists the provider, and from vendor
// documentation otherwise; `source` records which.
//
// `evidence` is what makes these pages worth publishing: the advertised SASL
// mechanisms and extensions are per-provider facts nobody else documents, and
// they map onto real product behaviour. `saslIr: false` is why Yandex needed a
// two-step AUTH fallback, and `move: false` is why organize falls back to
// COPY + STORE + EXPUNGE on that host.
//
// Prose lives in src/lib/connect/content/<locale>/<slug>.json, deliberately NOT
// in the next-intl `connect` namespace: the root layout ships every loaded
// namespace to the browser, so putting 106 providers' copy there would put all
// of it in the bundle of every marketing page, the home page included.

export const PROVIDER_CATEGORIES = [
  { id: "generic", label: "Any IMAP mailbox", anchor: "generic-imap" },
  { id: "consumer", label: "Consumer webmail", anchor: "consumer-webmail" },
  { id: "privacy", label: "Privacy-focused mail", anchor: "privacy-mail" },
  { id: "business", label: "Business & hosted mail", anchor: "business-mail" },
  { id: "hosting", label: "Web hosts with mail", anchor: "web-hosting" },
  { id: "cpanel", label: "cPanel & shared hosting", anchor: "cpanel-hosting" },
  { id: "selfhost", label: "Self-hosted mail servers", anchor: "self-hosted" },
  { id: "isp", label: "Internet service providers", anchor: "isp-mail" },
  { id: "regional", label: "Regional & international", anchor: "regional-mail" },
  { id: "blocked", label: "Limited or unsupported", anchor: "limited-support" },
];

export const PROVIDERS = [
  {
    slug: "imap",
    wave: 1,
    name: "Generic IMAP",
    category: "generic",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "aol",
    wave: 1,
    name: "AOL Mail",
    category: "consumer",
    domain: "aol.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.aol.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.aol.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK Welcome! IMAP Server up and ready to accept your request", "smtpAuthMechs": ["PLAIN", "LOGIN", "XOAUTH2", "OAUTHBEARER"], "smtpStarttls": false, "smtpMaxSize": "41697280"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "gmail",
    wave: 1,
    name: "Gmail",
    category: "consumer",
    domain: "gmail.com",
    hostPattern: "oauth",
    status: "supported",
    source: "ispdb+probe",
    // Deliberately null, though imap.gmail.com answered the probe like every
    // other host here. Gmail is the one provider we do not reach over IMAP: the
    // connector talks to gmail.googleapis.com with an OAuth token. Publishing an
    // IMAP settings table on this page would document a connection the product
    // does not make, and would send readers to generate an app password they
    // never use. The page explains OAuth instead.
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["OAUTHBEARER", "PLAIN", "PLAIN-CLIENTTOKEN", "XOAUTH2"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK Gimap ready for requests from 2001:4643:b9ff:0:2d3d:3074:e86a:6646 17ba6d92412a-343921bcb62mb13712213e", "smtpAuthMechs": ["LOGIN", "PLAIN", "XOAUTH2", "PLAIN-CLIENTTOKEN", "OAUTHBEARER", "XOAUTH"], "smtpStarttls": false, "smtpMaxSize": "35882577"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "gmx",
    wave: 1,
    name: "GMX",
    category: "consumer",
    domain: "gmx.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.gmx.net", "port": 993, "security": "tls"},
    smtp: {"host": "mail.gmx.net", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK [CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSE", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "141557760"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "icloud",
    wave: 1,
    name: "iCloud Mail",
    category: "consumer",
    domain: "icloud.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.mail.me.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.mail.me.com", "port": 587, "security": "starttls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["ATOKEN", "ATOKEN2", "PLAIN", "XOAUTH2"], "saslIr": true, "move": false, "idle": false, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 SASL-IR AUTH=ATOKEN AUTH=PLAIN AUTH=ATOKEN2 AUTH=XOAUTH2] (2632B238-1e86c56f9b73) p00-iscream-60-percent-84d6", "smtpAuthMechs": [], "smtpStarttls": true, "smtpMaxSize": "28319744"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "mail-com",
    wave: 2,
    name: "Mail.com",
    category: "consumer",
    domain: "mail.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.mail.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.mail.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK [CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSE", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "141557760"},
    locales: ["en"],
  },
  {
    slug: "mail-ru",
    wave: 2,
    name: "Mail.ru",
    category: "consumer",
    domain: "mail.ru",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.mail.ru", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.mail.ru", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": false, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4 ready", "smtpAuthMechs": ["PLAIN", "LOGIN", "XOAUTH2"], "smtpStarttls": false, "smtpMaxSize": "73400320"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "web-de",
    wave: 2,
    name: "WEB.DE",
    category: "consumer",
    domain: "web.de",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.web.de", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.web.de", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK [CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLU", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "141557760"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "yahoo",
    wave: 1,
    name: "Yahoo Mail",
    category: "consumer",
    domain: "yahoo.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "export.imap.mail.yahoo.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.mail.yahoo.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK Welcome! IMAP Server up and ready to accept your request", "smtpAuthMechs": ["PLAIN", "LOGIN", "XOAUTH2", "OAUTHBEARER"], "smtpStarttls": false, "smtpMaxSize": "41697280"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "yandex",
    wave: 1,
    name: "Yandex Mail",
    category: "consumer",
    domain: "yandex.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.yandex.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.yandex.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN", "XOAUTH2"], "saslIr": false, "move": true, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK Yandex IMAP4rev1 at mail-imap-production-main-835.vla.yp-c.yandex.net:993 ready to talk with 2001:4643:b9ff:0:2d3d:3074:e86a:6646:61713, 2026-Aug-31 19:37:", "smtpAuthMechs": ["LOGIN", "PLAIN", "XOAUTH2"], "smtpStarttls": true, "smtpMaxSize": "53477376"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "disroot",
    wave: 4,
    name: "Disroot",
    category: "privacy",
    domain: "disroot.org",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "disroot.org", "port": 993, "security": "tls"},
    smtp: {"host": "disroot.org", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "73400320"},
    locales: ["en"],
  },
  {
    slug: "hushmail",
    wave: 4,
    name: "Hushmail",
    category: "privacy",
    domain: "hushmail.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.hushmail.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.hushmail.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": false, "move": false, "idle": false, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4 ready", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "kolabnow",
    wave: 4,
    name: "KolabNow",
    category: "privacy",
    domain: "kolabnow.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.kolabnow.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.kolabnow.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE MUPDATE=mupdate://mupdate.kolabnow.com/ AUTH=PLAIN AUTH=LOGIN SASL-IR] int-imapf018.kolabnow.com Cyrus IMAP 3.6.6.", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "83886080"},
    locales: ["en"],
  },
  {
    slug: "mailbox-org",
    wave: 4,
    name: "mailbox.org",
    category: "privacy",
    domain: "mailbox.org",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.mailbox.org", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.mailbox.org", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": false, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE UIDPLUS LITERAL+ AUTH=PLAIN AUTH=LOGIN AUTH=OAUTHBEARER AUTH=XOAUTH2] Dovecot ready.", "smtpAuthMechs": ["PLAIN", "LOGIN", "XOAUTH2", "OAUTHBEARER"], "smtpStarttls": false, "smtpMaxSize": "143699726"},
    locales: ["en"],
  },
  {
    slug: "mailfence",
    wave: 5,
    name: "Mailfence",
    category: "privacy",
    domain: "mailfence.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.mailfence.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.mailfence.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4rev1 Service Ready", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "50000000"},
    locales: ["en"],
  },
  {
    slug: "posteo",
    wave: 5,
    name: "Posteo",
    category: "privacy",
    domain: "posteo.de",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "posteo.de", "port": 993, "security": "tls"},
    smtp: {"host": "posteo.de", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "143602323"},
    locales: ["en"],
  },
  {
    slug: "riseup",
    wave: 5,
    name: "Riseup",
    category: "privacy",
    domain: "riseup.net",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "mail.riseup.net", "port": 993, "security": "tls"},
    smtp: {"host": "mail.riseup.net", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] howdy, ready.", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "25600000"},
    locales: ["en"],
  },
  {
    slug: "runbox",
    wave: 5,
    name: "Runbox",
    category: "privacy",
    domain: "runbox.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "mail.runbox.com", "port": 993, "security": "tls"},
    smtp: {"host": "mail.runbox.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": false, "move": false, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4 ready", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "136314880"},
    locales: ["en"],
  },
  {
    slug: "soverin",
    wave: 5,
    name: "Soverin",
    category: "privacy",
    domain: "soverin.net",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.soverin.net", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.soverin.net", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=OAUTHBEARER AUTH=XOAUTH2] Dovecot ready.", "smtpAuthMechs": ["PLAIN", "LOGIN", "OAUTHBEARER", "XOAUTH2"], "smtpStarttls": false, "smtpMaxSize": "73400320"},
    locales: ["en"],
  },
  {
    slug: "startmail",
    wave: 10,
    name: "StartMail",
    category: "privacy",
    domain: "startmail.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.startmail.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.startmail.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE XLIST LITERAL+ AUTH=PLAIN] Dovecot (Ubuntu) ready.", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "39321600"},
    locales: ["en"],
  },
  {
    slug: "fastmail",
    wave: 1,
    name: "Fastmail",
    category: "business",
    domain: "fastmail.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.fastmail.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.fastmail.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK IMAP4 ready", "smtpAuthMechs": ["PLAIN", "LOGIN", "XOAUTH2", "OAUTHBEARER"], "smtpStarttls": false, "smtpMaxSize": "71000000"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "migadu",
    wave: 1,
    name: "Migadu",
    category: "business",
    domain: "migadu.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.migadu.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.migadu.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": false, "idle": false, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev2 IMAP4rev1 SASL-IR LITERAL- AUTH=PLAIN] Proxy Ready", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "52428800"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "purelymail",
    wave: 2,
    name: "Purelymail",
    category: "business",
    domain: "purelymail.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.purelymail.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.purelymail.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK PM IMAP ready", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "51200000"},
    locales: ["en"],
  },
  {
    slug: "rackspace",
    wave: 2,
    name: "Rackspace Email",
    category: "business",
    domain: "emailsrvr.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "secure.emailsrvr.com", "port": 993, "security": "tls"},
    smtp: {"host": "secure.emailsrvr.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] Server ready proxy7.mail.iad3b.rsapps.net", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "75000000"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "titan",
    wave: 2,
    name: "Titan Email",
    category: "business",
    domain: "titan.email",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.titan.email", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.titan.email", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": false, "idle": false, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 AUTH=PLAIN SASL-IR ID LITERAL-] At Your Service i.1014299d", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": true, "smtpMaxSize": "52428800"},
    locales: ["en"],
  },
  {
    slug: "zoho",
    wave: 1,
    name: "Zoho Mail",
    category: "business",
    domain: "zoho.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.zoho.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.zoho.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK svwall.zoho.com IMAP4 Server (Zoho Mail IMAP4rev1 Server version 1.0)", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "32505856"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "domeneshop",
    wave: 2,
    name: "Domeneshop",
    category: "hosting",
    domain: "domeneshop.no",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.domeneshop.no", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.domeneshop.no", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] director03 ready.", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "157286400"},
    locales: ["en"],
  },
  {
    slug: "dreamhost",
    wave: 2,
    name: "DreamHost",
    category: "hosting",
    domain: "dreamhost.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.dreamhost.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.dreamhost.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot (Ubuntu) ready.", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "40960000"},
    locales: ["en"],
  },
  {
    slug: "gandi",
    wave: 2,
    name: "Gandi",
    category: "hosting",
    domain: "gandi.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "mail.gandi.net", "port": 993, "security": "tls"},
    smtp: {"host": "mail.gandi.net", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ AUTH=PLAIN] Dovecot ready.", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "35651584"},
    locales: ["en"],
  },
  {
    slug: "godaddy",
    wave: 2,
    name: "GoDaddy",
    category: "hosting",
    domain: "secureserver.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.secureserver.net", "port": 993, "security": "tls"},
    smtp: {"host": "smtpout.secureserver.net", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": false, "move": false, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 UNSELECT ID CHILDREN NAMESPACE IDLE UIDPLUS AUTH=PLAIN] Fenix ready.", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "30000000"},
    locales: ["en"],
  },
  {
    slug: "hetzner",
    wave: 2,
    name: "Hetzner",
    category: "hosting",
    domain: "hetzner.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "mail.your-server.de", "port": 993, "security": "tls"},
    smtp: {"host": "mail.your-server.de", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot (Debian) ready.", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "104857600"},
    locales: ["en"],
  },
  {
    slug: "hostinger",
    wave: 3,
    name: "Hostinger",
    category: "hosting",
    domain: "hostinger.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.hostinger.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.hostinger.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Server ready.", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "48811212"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "infomaniak",
    wave: 3,
    name: "Infomaniak",
    category: "hosting",
    domain: "infomaniak.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "mail.infomaniak.com", "port": 993, "security": "tls"},
    smtp: {"host": "mail.infomaniak.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": false, "move": false, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4 ready", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "ionos",
    wave: 1,
    name: "IONOS",
    category: "hosting",
    domain: "ionos.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.ionos.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.ionos.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK [CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLU", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "141557760"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "loopia",
    wave: 3,
    name: "Loopia",
    category: "hosting",
    domain: "loopia.se",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "mailcluster.loopia.se", "port": 993, "security": "tls"},
    smtp: {"host": "mailcluster.loopia.se", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] Dovecot ready.", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "209715200"},
    locales: ["en"],
  },
  {
    slug: "namecheap",
    wave: 3,
    name: "Namecheap Private Email",
    category: "hosting",
    domain: "privateemail.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "mail.privateemail.com", "port": 993, "security": "tls"},
    smtp: {"host": "mail.privateemail.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": true, "smtpMaxSize": "83886080"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "one-com",
    wave: 3,
    name: "One.com",
    category: "hosting",
    domain: "one.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.one.com", "port": 993, "security": "tls"},
    smtp: {"host": "send.one.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "104857600"},
    locales: ["en"],
  },
  {
    slug: "ovh",
    wave: 3,
    name: "OVHcloud",
    category: "hosting",
    domain: "ovh.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "ssl0.ovh.net", "port": 993, "security": "tls"},
    smtp: {"host": "ssl0.ovh.net", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot on host 91 ready", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "104857600"},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "strato",
    wave: 3,
    name: "STRATO",
    category: "hosting",
    domain: "strato.de",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.strato.de", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.strato.de", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": false, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK [CAPABILITY IMAP4 IMAP4rev1 APPENDLIMIT=104857600 AUTH=PLAIN AUTH=LOGIN ENABLE ID IDLE MOVE LIST-EXTENDED NAMESPACE QUOTA SORT SPECIAL-USE UIDPLUS] IMAP se", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "104857600"},
    locales: ["en"],
  },
  {
    slug: "a2hosting",
    wave: 3,
    name: "A2 Hosting",
    category: "cpanel",
    domain: "a2hosting.com",
    hostPattern: "own-domain",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "bluehost",
    wave: 3,
    name: "Bluehost",
    category: "cpanel",
    domain: "bluehost.com",
    hostPattern: "own-domain",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "cpanel",
    wave: 3,
    name: "cPanel / WHM",
    category: "cpanel",
    domain: null,
    hostPattern: "own-domain",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en", "nb", "es", "fr", "zh"],
  },
  {
    slug: "greengeeks",
    wave: 3,
    name: "GreenGeeks",
    category: "cpanel",
    domain: "greengeeks.com",
    hostPattern: "own-domain",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "hostgator",
    wave: 4,
    name: "HostGator",
    category: "cpanel",
    domain: "hostgator.com",
    hostPattern: "own-domain",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "inmotion",
    wave: 4,
    name: "InMotion Hosting",
    category: "cpanel",
    domain: "inmotionhosting.com",
    hostPattern: "own-domain",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "krystal",
    wave: 4,
    name: "Krystal",
    category: "cpanel",
    domain: "krystal.uk",
    hostPattern: "own-domain",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "plesk",
    wave: 4,
    name: "Plesk",
    category: "cpanel",
    domain: null,
    hostPattern: "own-domain",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "scalahosting",
    wave: 4,
    name: "ScalaHosting",
    category: "cpanel",
    domain: "scalahosting.com",
    hostPattern: "own-domain",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "siteground",
    wave: 4,
    name: "SiteGround",
    category: "cpanel",
    domain: "siteground.com",
    hostPattern: "own-domain",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "tsohost",
    wave: 4,
    name: "Tsohost",
    category: "cpanel",
    domain: "tsohost.com",
    hostPattern: "own-domain",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "axigen",
    wave: 8,
    name: "Axigen",
    category: "selfhost",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "dovecot",
    wave: 8,
    name: "Dovecot",
    category: "selfhost",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "icewarp",
    wave: 8,
    name: "IceWarp",
    category: "selfhost",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "mailcow",
    wave: 8,
    name: "mailcow",
    category: "selfhost",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "mailinabox",
    wave: 8,
    name: "Mail-in-a-Box",
    category: "selfhost",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "mdaemon",
    wave: 9,
    name: "MDaemon",
    category: "selfhost",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "open-xchange",
    wave: 9,
    name: "Open-Xchange",
    category: "selfhost",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "poste-io",
    wave: 9,
    name: "Poste.io",
    category: "selfhost",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "smartermail",
    wave: 9,
    name: "SmarterMail",
    category: "selfhost",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "synology",
    wave: 9,
    name: "Synology MailPlus",
    category: "selfhost",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "zimbra",
    wave: 9,
    name: "Zimbra",
    category: "selfhost",
    domain: null,
    hostPattern: "own-server",
    status: "supported",
    source: "pattern",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "att",
    wave: 6,
    name: "AT&T Mail",
    category: "isp",
    domain: "att.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.mail.att.net", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.mail.att.net", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK Welcome! IMAP Server up and ready to accept your request", "smtpAuthMechs": ["PLAIN", "LOGIN", "XOAUTH2", "OAUTHBEARER"], "smtpStarttls": false, "smtpMaxSize": "41697280"},
    locales: ["en"],
  },
  {
    slug: "bigpond",
    wave: 6,
    name: "Telstra BigPond",
    category: "isp",
    domain: "bigpond.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.telstra.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.telstra.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": true, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SPECIAL-USE LITERAL+ AUTH=PLAIN AUTH=LOGIN] imap ready - claprdcma08", "smtpAuthMechs": ["LOGIN", "PLAIN", "XOAUTH2"], "smtpStarttls": false, "smtpMaxSize": "31457280"},
    locales: ["en"],
  },
  {
    slug: "bluewin",
    wave: 6,
    name: "Bluewin (Swisscom)",
    category: "isp",
    domain: "bluewin.ch",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imaps.bluewin.ch", "port": 993, "security": "tls"},
    smtp: {"host": "smtpauths.bluewin.ch", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=OAUTHBEARER AUTH=XOAUTH2] Server ready.", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "26214400"},
    locales: ["en"],
  },
  {
    slug: "centurylink",
    wave: 6,
    name: "CenturyLink",
    category: "isp",
    domain: "centurylink.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "mail.centurylink.net", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.centurylink.net", "port": 587, "security": "starttls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN"], "saslIr": false, "move": false, "idle": false, "uidplus": false, "specialUse": true, "banner": "* OK Mail2World IMAP4 Server v3.0.7625.15046 64bit (LUWEB06OC) ready", "smtpAuthMechs": ["LOGIN"], "smtpStarttls": true, "smtpMaxSize": "0"},
    locales: ["en"],
  },
  {
    slug: "comcast",
    wave: 6,
    name: "Comcast Xfinity",
    category: "isp",
    domain: "comcast.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.comcast.net", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.comcast.net", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN AUTH=OAUTHBEARER AUTH=XOAUTH2] Dovecot ready.", "smtpAuthMechs": ["LOGIN", "PLAIN", "XOAUTH2"], "smtpStarttls": false, "smtpMaxSize": "36700160"},
    locales: ["en"],
  },
  {
    slug: "cox",
    wave: 6,
    name: "Cox",
    category: "isp",
    domain: "cox.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "export.imap.mail.yahoo.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.mail.yahoo.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK Welcome! IMAP Server up and ready to accept your request", "smtpAuthMechs": ["PLAIN", "LOGIN", "XOAUTH2", "OAUTHBEARER"], "smtpStarttls": false, "smtpMaxSize": "41697280"},
    locales: ["en"],
  },
  {
    slug: "earthlink",
    wave: 6,
    name: "EarthLink",
    category: "isp",
    domain: "earthlink.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.earthlink.net", "port": 993, "security": "tls"},
    smtp: {"host": "smtpauth.earthlink.net", "port": 587, "security": "starttls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["CRAM-MD5", "EL-TAC", "EL-VOICE"], "saslIr": false, "move": false, "idle": false, "uidplus": true, "specialUse": false, "banner": "* OK earthlink.net IMAP Service 13250 imapd EL_0_1_44_OIM_1_P at oim-prod10.sys.elnk.net ready", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": true, "smtpMaxSize": "52428800"},
    locales: ["en"],
  },
  {
    slug: "free-fr",
    wave: 7,
    name: "Free",
    category: "isp",
    domain: "free.fr",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.free.fr", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.free.fr", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": false, "move": false, "idle": false, "uidplus": false, "specialUse": false, "banner": "* OK IMAP4 ready", "smtpAuthMechs": ["PLAIN", "LOGIN", "CRAM-MD5", "DIGEST-MD5"], "smtpStarttls": false, "smtpMaxSize": "78643200"},
    locales: ["en"],
  },
  {
    slug: "freenet",
    wave: 7,
    name: "freenet",
    category: "isp",
    domain: "freenet.de",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "mx.freenet.de", "port": 993, "security": "tls"},
    smtp: {"host": "mx.freenet.de", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 LOGIN-REFERRALS ID ENABLE IDLE SASL-IR LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "209715200"},
    locales: ["en"],
  },
  {
    slug: "frontier",
    wave: 10,
    name: "Frontier",
    category: "isp",
    domain: "frontier.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.frontier.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.frontier.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": false, "idle": false, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4rev1 proxy server ready", "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "iinet",
    wave: 7,
    name: "iiNet",
    category: "isp",
    domain: "iinet.net.au",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "mail.iinet.net.au", "port": 993, "security": "tls"},
    smtp: {"host": "mail.iinet.net.au", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": true, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SPECIAL-USE COMPRESS=DEFLATE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] imap ready - cma-kakadu0", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": true, "smtpMaxSize": "83886080"},
    locales: ["en"],
  },
  {
    slug: "interia",
    wave: 7,
    name: "Interia",
    category: "isp",
    domain: "interia.pl",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "poczta.interia.pl", "port": 993, "security": "tls"},
    smtp: {"host": "poczta.interia.pl", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": false, "move": false, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN ID XLIST NAMESPACE IDLE STARTTLS AUTH=PLAIN] IMAP4 ready.", "smtpAuthMechs": ["PLAIN", "LOGIN", "PLAIN", "LOGIN", "PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "157286400"},
    locales: ["en"],
  },
  {
    slug: "kpn",
    wave: 7,
    name: "KPN",
    category: "isp",
    domain: "kpnmail.nl",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.kpnmail.nl", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.kpnmail.nl", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Server ready", "smtpAuthMechs": ["LOGIN"], "smtpStarttls": false, "smtpMaxSize": "52428800"},
    locales: ["en"],
  },
  {
    slug: "laposte",
    wave: 7,
    name: "La Poste",
    category: "isp",
    domain: "laposte.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.laposte.net", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.laposte.net", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": false, "move": false, "idle": false, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4 ready", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "15800000"},
    locales: ["en"],
  },
  {
    slug: "o2-pl",
    wave: 7,
    name: "o2.pl",
    category: "isp",
    domain: "o2.pl",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "poczta.o2.pl", "port": 993, "security": "tls"},
    smtp: {"host": "poczta.o2.pl", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": false, "move": true, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4 ready", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "onet",
    wave: 7,
    name: "Onet Poczta",
    category: "isp",
    domain: "onet.pl",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.poczta.onet.pl", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.poczta.onet.pl", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN", "XOAUTH2"], "saslIr": true, "move": false, "idle": false, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID LITERAL+ AUTH=PLAIN AUTH=LOGIN AUTH=XOAUTH2] Onet server ready.", "smtpAuthMechs": ["PLAIN", "LOGIN", "XOAUTH2"], "smtpStarttls": false, "smtpMaxSize": "90000000"},
    locales: ["en"],
  },
  {
    slug: "online-no",
    wave: 7,
    name: "Online.no",
    category: "isp",
    domain: "online.no",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.online.no", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.online.no", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4REV1 LITERAL+ UTF8=ALL STATUS=SIZE STARTTLS SASL-IR AUTH=LOGIN ID] mail170c60 IMAP4rev1 Bigfoot", "smtpAuthMechs": ["LOGIN"], "smtpStarttls": true, "smtpMaxSize": "52428800"},
    locales: ["en"],
  },
  {
    slug: "optimum",
    wave: 10,
    name: "Optimum",
    category: "isp",
    domain: "optimum.net",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "mail.optimum.net", "port": 993, "security": "tls"},
    smtp: {"host": "mail.optimum.net", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": false, "move": true, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4 server ready", "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "optus",
    wave: 7,
    name: "Optus",
    category: "isp",
    domain: "optusnet.com.au",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "mail.optusnet.com.au", "port": 993, "security": "tls"},
    smtp: {"host": "mail.optusnet.com.au", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": true, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SPECIAL-USE COMPRESS=DEFLATE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] imap ready - cma-waratah", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": true, "smtpMaxSize": "83886080"},
    locales: ["en"],
  },
  {
    slug: "orange-fr",
    wave: 7,
    name: "Orange",
    category: "isp",
    domain: "orange.fr",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.orange.fr", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.orange.fr", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": false, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "46000000"},
    locales: ["en"],
  },
  {
    slug: "rogers",
    wave: 10,
    name: "Rogers",
    category: "isp",
    domain: "rogers.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.broadband.rogers.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.broadband.rogers.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK Welcome! IMAP Server up and ready to accept your request", "smtpAuthMechs": ["PLAIN", "LOGIN", "XOAUTH2", "OAUTHBEARER"], "smtpStarttls": false, "smtpMaxSize": "41697280"},
    locales: ["en"],
  },
  {
    slug: "sapo",
    wave: 8,
    name: "SAPO",
    category: "isp",
    domain: "sapo.pt",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.sapo.pt", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.sapo.pt", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] Welcome to PTMail", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": true, "smtpMaxSize": "31457280"},
    locales: ["en"],
  },
  {
    slug: "seznam",
    wave: 8,
    name: "Seznam",
    category: "isp",
    domain: "seznam.cz",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.seznam.cz", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.seznam.cz", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": false, "uidplus": true, "specialUse": false, "banner": "* OK Seznam IMAP server ready", "smtpAuthMechs": ["PLAIN", "LOGIN", "OAUTHBEARER", "XOAUTH2"], "smtpStarttls": false, "smtpMaxSize": "52428800"},
    locales: ["en"],
  },
  {
    slug: "sfr",
    wave: 10,
    name: "SFR",
    category: "isp",
    domain: "sfr.fr",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.sfr.fr", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.sfr.fr", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": false, "move": false, "idle": false, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4 ready", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "20971520"},
    locales: ["en"],
  },
  {
    slug: "t-online",
    wave: 8,
    name: "T-Online",
    category: "isp",
    domain: "t-online.de",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "secureimap.t-online.de", "port": 993, "security": "tls"},
    smtp: {"host": "securesmtp.t-online.de", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": [], "saslIr": false, "move": false, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4 IMAP4rev1 QUOTA LITERAL+ NAMESPACE UIDPLUS IDLE SORT] IMAP Proxy ready (secureimap.t-online.de)", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "52428800"},
    locales: ["en"],
  },
  {
    slug: "telenet",
    wave: 8,
    name: "Telenet",
    category: "isp",
    domain: "telenet.be",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.telenet.be", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.telenet.be", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4rev1 proxy server ready", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "20971520"},
    locales: ["en"],
  },
  {
    slug: "verizon",
    wave: 8,
    name: "Verizon",
    category: "isp",
    domain: "verizon.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.aol.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.aol.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["OAUTHBEARER", "PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": true, "banner": "* OK Welcome! IMAP Server up and ready to accept your request", "smtpAuthMechs": ["PLAIN", "LOGIN", "XOAUTH2", "OAUTHBEARER"], "smtpStarttls": false, "smtpMaxSize": "41697280"},
    locales: ["en"],
  },
  {
    slug: "wp-pl",
    wave: 10,
    name: "WP.pl",
    category: "isp",
    domain: "wp.pl",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.wp.pl", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.wp.pl", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": false, "move": true, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4 ready", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "xtra",
    wave: 10,
    name: "Spark Xtra",
    category: "isp",
    domain: "xtra.co.nz",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.xtra.co.nz", "port": 993, "security": "tls"},
    smtp: {"host": "send.xtra.co.nz", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": false, "move": false, "idle": false, "uidplus": true, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 UIDPLUS NAMESPACE ID AUTH=PLAIN AUTH=LOGIN] imap.xtra.co.nz IMAP4 server ready", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "104857600"},
    locales: ["en"],
  },
  {
    slug: "ziggo",
    wave: 8,
    name: "Ziggo",
    category: "isp",
    domain: "ziggo.nl",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.ziggo.nl", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.ziggo.nl", "port": 587, "security": "starttls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": false, "move": false, "idle": false, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 AUTH=PLAIN] VodafoneZiggo server ready.", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": true, "smtpMaxSize": "31457280"},
    locales: ["en"],
  },
  {
    slug: "aliyun",
    wave: 5,
    name: "Alibaba Mail",
    category: "regional",
    domain: "aliyun.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.aliyun.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.aliyun.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["EXTERNAL", "XOAUTH", "XOAUTH2"], "saslIr": true, "move": false, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK AliYun IMAP Server Ready", "smtpAuthMechs": ["PLAIN", "LOGIN", "XOAUTH2", "XALIOAUTH"], "smtpStarttls": false, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "bol",
    wave: 5,
    name: "BOL",
    category: "regional",
    domain: "bol.com.br",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.bol.com.br", "port": 993, "security": "tls"},
    smtp: {"host": "smtps.bol.com.br", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": false, "uidplus": true, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4 IMAP4rev1 QUOTA UIDPLUS ID NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY SORT NAMESPACE SASL-IR AUTH=PLAIN AUTH=LOGIN] Dovecot re", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "34865152"},
    locales: ["en"],
  },
  {
    slug: "daum",
    wave: 5,
    name: "Daum",
    category: "regional",
    domain: "daum.net",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.daum.net", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.daum.net", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": true, "idle": false, "uidplus": true, "specialUse": false, "banner": "* OK IMAP4 ready XSX6wDpSJ4c", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "73400320"},
    locales: ["en"],
  },
  {
    slug: "naver",
    wave: 5,
    name: "Naver",
    category: "regional",
    domain: "naver.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.naver.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.naver.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN"], "saslIr": true, "move": true, "idle": false, "uidplus": true, "specialUse": true, "banner": "* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR ID CHILDREN UIDPLUS LIST-EXTENDED SPECIAL-USE UNSELECT QUOTA MOVE AUTH=PLAIN APPENDLIMIT=41943040] Naver Imap Server", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": false, "smtpMaxSize": "39845888"},
    locales: ["en"],
  },
  {
    slug: "netease-126",
    wave: 5,
    name: "NetEase 126",
    category: "regional",
    domain: "126.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.126.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.126.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["XOAUTH2"], "saslIr": true, "move": false, "idle": false, "uidplus": true, "specialUse": true, "banner": "* OK Coremail System IMap Server Ready(126com[6c62234a7721d45811debf430915950d])", "smtpAuthMechs": ["LOGIN", "PLAIN", "XOAUTH2"], "smtpStarttls": true, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "netease-163",
    wave: 5,
    name: "NetEase 163",
    category: "regional",
    domain: "163.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.163.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.163.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["XOAUTH2"], "saslIr": true, "move": false, "idle": false, "uidplus": true, "specialUse": true, "banner": "* OK Coremail System IMap Server Ready(163com[10774b260cc7a37d26d71b52404dcf5c])", "smtpAuthMechs": ["LOGIN", "PLAIN", "XOAUTH2"], "smtpStarttls": true, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "qq",
    wave: 6,
    name: "QQ Mail",
    category: "regional",
    domain: "qq.com",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.qq.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.qq.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4 IMAP4rev1 ID AUTH=PLAIN AUTH=LOGIN AUTH=XOAUTH2 NAMESPACE] QQMail XMIMAP4Server ready", "smtpAuthMechs": ["LOGIN", "PLAIN", "XOAUTH", "XOAUTH2"], "smtpStarttls": false, "smtpMaxSize": "73400320"},
    locales: ["en"],
  },
  {
    slug: "sina",
    wave: 6,
    name: "Sina Mail",
    category: "regional",
    domain: "sina.com",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.sina.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.sina.com", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": [], "saslIr": false, "move": false, "idle": false, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 ID] sina imap server ready", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": true, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "terra",
    wave: 6,
    name: "Terra",
    category: "regional",
    domain: "terra.com.br",
    hostPattern: "shared",
    status: "supported",
    source: "vendor+probe",
    imap: {"host": "imap.terra.com.br", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.terra.com.br", "port": 465, "security": "tls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": true, "uidplus": false, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] terra.com.br.", "smtpAuthMechs": ["LOGIN", "PLAIN"], "smtpStarttls": false, "smtpMaxSize": "41943040"},
    locales: ["en"],
  },
  {
    slug: "uol",
    wave: 6,
    name: "UOL",
    category: "regional",
    domain: "uol.com.br",
    hostPattern: "shared",
    status: "supported",
    source: "ispdb+probe",
    imap: {"host": "imap.uol.com.br", "port": 993, "security": "tls"},
    smtp: {"host": "smtps.uol.com.br", "port": 587, "security": "starttls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["LOGIN", "PLAIN"], "saslIr": true, "move": false, "idle": false, "uidplus": true, "specialUse": false, "banner": "* OK [CAPABILITY IMAP4 IMAP4rev1 QUOTA UIDPLUS ID NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY SORT NAMESPACE SASL-IR AUTH=PLAIN AUTH=LOGIN] Dovecot re", "smtpAuthMechs": ["PLAIN", "LOGIN"], "smtpStarttls": true, "smtpMaxSize": "34865152"},
    locales: ["en"],
  },
  {
    slug: "hey",
    wave: 9,
    name: "HEY",
    category: "blocked",
    domain: "hey.com",
    hostPattern: "shared",
    status: "limited",
    source: "UNVERIFIED",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "office365",
    wave: 9,
    name: "Microsoft 365",
    category: "blocked",
    domain: "office365.com",
    hostPattern: "shared",
    status: "limited",
    source: "ispdb+probe",
    imap: {"host": "outlook.office365.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp.office365.com", "port": 587, "security": "starttls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["PLAIN", "XOAUTH2"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK Microsoft Exchange IMAP4 service ready. 28e79741-268c-4463-b2b6-8ae5b453b488 (tcpproxy/15.21.0360.006 BACKENDAUTHENTICATE) [TwBMADEAUAAyADcAOQBDAEEAMAAwADI", "smtpAuthMechs": [], "smtpStarttls": true, "smtpMaxSize": "157286400"},
    locales: ["en"],
  },
  {
    slug: "outlook",
    wave: 9,
    name: "Outlook.com",
    category: "blocked",
    domain: "outlook.com",
    hostPattern: "shared",
    status: "limited",
    source: "ispdb+probe",
    imap: {"host": "outlook.office365.com", "port": 993, "security": "tls"},
    smtp: {"host": "smtp-mail.outlook.com", "port": 587, "security": "starttls"},
    evidence: {"verifiedOn": "2026-08-31", "reachable": true, "authMechs": ["XOAUTH2"], "saslIr": true, "move": true, "idle": true, "uidplus": true, "specialUse": false, "banner": "* OK Microsoft Exchange IMAP4 service ready. f7727043-334d-49cc-8f5e-3d93fc232c38 (tcpproxy/15.21.0360.006 BACKENDAUTHENTICATE) [TwBMADEAUAAyADcAOQBDAEEAMAAwADI", "smtpAuthMechs": [], "smtpStarttls": true, "smtpMaxSize": "157286400"},
    locales: ["en"],
  },
  {
    slug: "proton",
    wave: 9,
    name: "Proton Mail",
    category: "blocked",
    domain: "protonmail.com",
    hostPattern: "shared",
    status: "limited",
    source: "UNVERIFIED",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
  {
    slug: "tutanota",
    wave: 9,
    name: "Tuta",
    category: "blocked",
    domain: "tutanota.com",
    hostPattern: "shared",
    status: "limited",
    source: "UNVERIFIED",
    imap: null,
    smtp: null,
    evidence: {"verifiedOn": "2026-08-31", "reachable": false, "authMechs": [], "saslIr": null, "move": null, "idle": null, "uidplus": null, "specialUse": null, "banner": null, "smtpAuthMechs": [], "smtpStarttls": null, "smtpMaxSize": null},
    locales: ["en"],
  },
];

const BY_SLUG = new Map(PROVIDERS.map((p) => [p.slug, p]));

export function getProvider(slug) {
  return BY_SLUG.get(slug) ?? null;
}

export function providerSlugs() {
  return PROVIDERS.map((p) => p.slug);
}

/** Locales a provider has copy for. Drives hreflang, so it must not claim a
 *  translation that does not exist: a bad alternate is worse than none. */
export function providerLocales(slug) {
  return getProvider(slug)?.locales ?? ['en'];
}

export function providersByCategory(category) {
  return PROVIDERS.filter((p) => p.category === category);
}

